package com.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Validates that the JDK 11 → 21 migration was applied correctly.
 *
 * <p>These tests are auto-generated by the auto-remediation system and are
 * intentionally simple: they verify (a) the JVM version at runtime is Java 21+
 * and (b) Java 21 language features compile and behave correctly.
 *
 * <p>Feel free to expand them with project-specific migration checks.
 */
class AutoRemediationMigrationTest {

    /** Java 21 record — fails to compile on Java 11 source level. */
    record MigrationMarker(int javaVersion, String status) {}

    @Test
    void javaVersionIsAtLeast21() {
        int feature = Runtime.version().feature();
        assertTrue(
            feature >= 21,
            "Expected JVM 21+, but running on Java " + feature + ". "
                + "Check that the build and runtime images were updated to Java 21."
        );
    }

    @Test
    void java21RecordCompiles() {
        // Records were finalised in Java 16.  If this compiles and runs,
        // the compiler target has been raised beyond 11.
        var marker = new MigrationMarker(21, "migrated");
        assertEquals(21, marker.javaVersion());
        assertEquals("migrated", marker.status());
    }

    @Test
    void patternMatchingForSwitchWorks() {
        // Pattern matching for switch was finalised in Java 21 (JEP 441).
        Object value = Integer.valueOf(42);
        String result = switch (value) {
            case Integer i when i > 0 -> "positive int: " + i;
            case Integer i            -> "non-positive int: " + i;
            case String s             -> "string: " + s;
            default                   -> "other";
        };
        assertEquals("positive int: 42", result);
    }
}
